
package soc.storm.situation.test.avro;

import org.apache.avro.Schema;

public class AvroSchemeTest {

    private static String topicProperties014 = "{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"}]}},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties015 = "{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"},{\"name\":\"notafter\",\"type\":[\"string\",\"null\"]},{\"name\":\"notbefore\",\"type\":[\"string\",\"null\"]},{\"name\":\"public_key\",\"type\":[\"string\",\"null\"]}]}},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties016 = "{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":{\"namespace\":\"skyeye_ssl_cert\",\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"},{\"name\":\"notafter\",\"type\":[\"string\",\"null\"]},{\"name\":\"notbefore\",\"type\":[\"string\",\"null\"]},{\"name\":\"public_key\",\"type\":[\"string\",\"null\"]}]}},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties017 = "[{\"namespace\":\"skyeye_ssl_cert\",\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"},{\"name\":\"notafter\",\"type\":[\"string\",\"null\"]},{\"name\":\"notbefore\",\"type\":[\"string\",\"null\"]},{\"name\":\"public_key\",\"type\":[\"string\",\"null\"]}]},{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":\"skyeye_ssl_cert.skyeye_ssl_cert\"},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}]";

    private static String topicProperties018 = "{\"namespace\":\"skyeye_tcpflow\",\"type\":\"record\",\"name\":\"skyeye_tcpflow\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"downlink_length\"},{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"map<string,string>\",\"null\"],\"name\":\"geo_sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"proto\"},{\"type\":[\"string\",\"null\"],\"name\":\"down_payload\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_os\"},{\"type\":[\"string\",\"null\"],\"name\":\"client_os\"},{\"type\":[\"string\",\"null\"],\"name\":\"src_mac\"},{\"type\":[\"string\",\"null\"],\"name\":\"status\"},{\"type\":[\"string\",\"null\"],\"name\":\"dst_mac\"},{\"type\":[\"string\",\"null\"],\"name\":\"dtime\"},{\"type\":[\"string\",\"null\"],\"name\":\"stime\"},{\"type\":[\"map<string,string>\",\"null\"],\"name\":\"geo_dip\"},{\"type\":[\"string\",\"null\"],\"name\":\"up_payload\"},{\"type\":[\"string\",\"null\"],\"name\":\"summary\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"long\",\"null\"],\"name\":\"uplink_length\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties019 = "{\"namespace\":\"skyeye_dns\",\"type\":\"record\",\"name\":\"skyeye_dns\",\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"count\"},{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"addr\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":[\"int\",\"null\"],\"name\":\"reply_code\"},{\"type\":[\"string\",\"null\"],\"name\":\"host\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"int\",\"null\"],\"name\":\"dns_type\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"host_md5\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"cname\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_dip\"},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\",\"null\"],\"name\":\"mx\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties020 = "{\"namespace\":\"skyeye_sql\",\"type\":\"record\",\"name\":\"skyeye_sql\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"db_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"proto\"},{\"type\":[\"string\",\"null\"],\"name\":\"normal_ret\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"db_type\"},{\"type\":[\"string\",\"null\"],\"name\":\"ret_code\"},{\"type\":[\"string\",\"null\"],\"name\":\"sql_info\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"type\":[\"string\",\"null\"],\"name\":\"user\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_dip\"},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_sip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties021 = "{\"namespace\":\"skyeye_mail\",\"type\":\"record\",\"name\":\"skyeye_mail\",\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"cc\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"references\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_sip\"},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"subject\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"proto\"},{\"type\":[\"string\",\"null\"],\"name\":\"mid\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"to\"},{\"type\":[{\"items\":{\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"attach_md5\"},{\"type\":[\"string\",\"null\"],\"name\":\"mime_type\"},{\"type\":[\"string\",\"null\"],\"name\":\"name\"}],\"type\":\"record\",\"name\":\"element\"},\"type\":\"array\"},\"null\"],\"name\":\"attachment\"},{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"returnpath\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_dip\"},{\"type\":[{\"items\":\"string\",\"type\":\"array\"},\"null\"],\"name\":\"received\"},{\"type\":[\"string\",\"null\"],\"name\":\"`from`\"},{\"type\":[\"string\",\"null\"],\"name\":\"plain\"},{\"type\":[\"string\",\"null\"],\"name\":\"bcc\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"time\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties022 = "{\"namespace\":\"skyeye_mail\",\"type\":\"record\",\"name\":\"skyeye_mail\",\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"cc\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"references\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_sip\"},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"subject\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"proto\"},{\"type\":[\"string\",\"null\"],\"name\":\"mid\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"to\"},{\"type\":[{\"items\":{\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"attach_md5\"},{\"type\":[\"string\",\"null\"],\"name\":\"mime_type\"},{\"type\":[\"string\",\"null\"],\"name\":\"name\"}],\"type\":\"record\",\"name\":\"element\"},\"type\":\"array\"},\"null\"],\"name\":\"attachment\"},{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"returnpath\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_dip\"},{\"type\":[{\"items\":\"string\",\"type\":\"array\"},\"null\"],\"name\":\"received\"},{\"type\":[\"string\",\"null\"],\"name\":\"from\"},{\"type\":[\"string\",\"null\"],\"name\":\"plain\"},{\"type\":[\"string\",\"null\"],\"name\":\"bcc\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"time\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties023 = "{\"namespace\":\"skyeye_mail\",\"type\":\"record\",\"name\":\"skyeye_mail\",\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"cc\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"references\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_sip\"},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"subject\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"proto\"},{\"type\":[\"string\",\"null\"],\"name\":\"mid\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"to\"},{\"type\":[{\"items\":{\"fields\":[{\"type\":[\"string\",\"null\"],\"name\":\"attach_md5\"},{\"type\":[\"string\",\"null\"],\"name\":\"mime_type\"},{\"type\":[\"string\",\"null\"],\"name\":\"name\"}],\"type\":\"record\",\"name\":\"element\"},\"type\":\"array\"},\"null\"],\"name\":\"attachment\"},{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"returnpath\"},{\"type\":[{\"values\":\"string\",\"type\":\"map\"},\"null\"],\"name\":\"geo_dip\"},{\"type\":[{\"items\":\"string\",\"type\":\"array\"},\"null\"],\"name\":\"received\"},{\"type\":[\"string\",\"null\"],\"name\":\"from\"},{\"type\":[\"string\",\"null\"],\"name\":\"plain\"},{\"type\":[\"string\",\"null\"],\"name\":\"bcc\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"time\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    public static void main(String[] args) {
        Schema topicSchema = new Schema.Parser().parse(topicProperties023);
        System.out.println(topicSchema);
    }
}
