
package soc.storm.situation.test.avro;

import org.apache.avro.Schema;

public class AvroSchemeTest {

    private static String topicProperties014 = "{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"}]}},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties015 = "{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"},{\"name\":\"notafter\",\"type\":[\"string\",\"null\"]},{\"name\":\"notbefore\",\"type\":[\"string\",\"null\"]},{\"name\":\"public_key\",\"type\":[\"string\",\"null\"]}]}},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties016 = "{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":{\"namespace\":\"skyeye_ssl_cert\",\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"},{\"name\":\"notafter\",\"type\":[\"string\",\"null\"]},{\"name\":\"notbefore\",\"type\":[\"string\",\"null\"]},{\"name\":\"public_key\",\"type\":[\"string\",\"null\"]}]}},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}";

    private static String topicProperties017 = "[{\"namespace\":\"skyeye_ssl_cert\",\"type\":\"record\",\"name\":\"skyeye_ssl_cert\",\"fields\":[{\"name\":\"issuer_name\",\"type\":\"string\"},{\"name\":\"notafter\",\"type\":[\"string\",\"null\"]},{\"name\":\"notbefore\",\"type\":[\"string\",\"null\"]},{\"name\":\"public_key\",\"type\":[\"string\",\"null\"]}]},{\"namespace\":\"skyeye_ssl\",\"type\":\"record\",\"name\":\"skyeye_ssl\",\"fields\":[{\"type\":[\"long\",\"null\"],\"name\":\"found_time\"},{\"type\":[\"string\",\"null\"],\"name\":\"sip\"},{\"type\":[\"string\",\"null\"],\"name\":\"server_name\"},{\"type\":[\"string\",\"null\"],\"name\":\"access_time\"},{\"type\":{\"type\":\"array\",\"items\":\"skyeye_ssl_cert.skyeye_ssl_cert\"},\"name\":\"cert\"},{\"type\":[\"string\",\"null\"],\"name\":\"session_id\"},{\"type\":[\"string\",\"null\"],\"name\":\"serial_num\"},{\"type\":[\"string\",\"null\"],\"name\":\"sipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"dipv6\"},{\"type\":[\"string\",\"null\"],\"name\":\"version\"},{\"name\":\"geo_sip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"string\",\"null\"],\"name\":\"user_name\"},{\"type\":[\"int\",\"null\"],\"name\":\"dport\"},{\"name\":\"geo_dip\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"]},{\"type\":[\"int\",\"null\"],\"name\":\"sport\"},{\"type\":[\"string\",\"null\"],\"name\":\"dip\"},{\"type\":[\"string\"],\"name\":\"partition_time\"}]}]";

    public static void main(String[] args) {
        Schema topicSchema = new Schema.Parser().parse(topicProperties016);
        System.out.println(topicSchema);
    }
}
