/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestByteArrayJni */

#ifndef _Included_TestByteArrayJni
#define _Included_TestByteArrayJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestByteArrayJni
 * Method:    encrypt
 * Signature: ([BIILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_TestByteArrayJni_encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jstring);

/*
 * Class:     TestByteArrayJni
 * Method:    decrypt
 * Signature: ([BIILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_TestByteArrayJni_decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
